# 1D - Tensor -Vector

In [6]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6],[10,20,90]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 90]]


In [8]:
print("Dimension of a > ", a.ndim)

Dimension of a >  2
