# 2D - Tensor - Matrix

In [1]:
import numpy as np

In [7]:
a = np.array([[10,120,90909],[90,123,8979],[1238,8723,90917230]])
print(a)

[[      10      120    90909]
 [      90      123     8979]
 [    1238     8723 90917230]]


In [9]:
print("Dimension of a > ", a.ndim)

Dimension of a >  2
