# 3D - Tensor 

In [1]:
import numpy as np

In [12]:
a = np.array([[[1,2,3],[4,5,6]],
              [[10,20,30],[40,50,60]]])
print(a)
a.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


3

# 4D - Tensor 

In [11]:
b = np.array(
    [
        [
            [
                [1,2,3], [4,5,6]
            ]
        ]
    ]
)
print(b)
b.ndim

[[[[1 2 3]
   [4 5 6]]]]


4

# 5D - Tensor 

In [16]:
c = np.array([[[[[1,2,3]]]]])
print(c)
c.ndim

[[[[[1 2 3]]]]]


5

# 6D - Tensor 

In [8]:
d = np.array(
    [[[[[[1,2,3,4,5]]]]]]
)
print(d, '\n' , 'Dim of d > ', d.ndim)

[[[[[[1 2 3 4 5]]]]]] 
 Dim of d >  6


# 7D - Tensor 

In [6]:
e = np.array(
    [[[[[[[1,2,3,4],[6,7,8,9]]]]]]]
)
print(e, '\n' , 'Dim of e > ', e.ndim)

[[[[[[[1 2 3 4]
      [6 7 8 9]]]]]]] 
 Dim of e >  7


# 10D - Tensor

In [10]:
x = np.array(
    [[[[[[[[[[1,2,3,4,5],[0,8,6,7,8],[5,3,2,1,6]]]]]]]]]]
)
print(x, '\n' , 'Dim of x > ', x.ndim)

[[[[[[[[[[1 2 3 4 5]
         [0 8 6 7 8]
         [5 3 2 1 6]]]]]]]]]] 
 Dim of x >  10
